version: '2.2'
services:
  notebooks:
    restart: always
    build:
      context: ./my-notebooks
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./my-notebooks:/home/jovyan/work
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  observer:
    restart: always
    image: observertc/observer:1.0.0-beta
    ports:
      - 7080:7080
    environment:
      - MICRONAUT_CONFIG_FILES=/my-config.yaml
    volumes:
      - ./observer-config/config.yaml:/my-config.yaml
    extra_hosts:
          - "host.docker.internal:host-gateway" 
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    extra_hosts:
          - "host.docker.internal:host-gateway" 
  mongo-express:
    image: mongo-express
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy

  mediasoup_sfu:
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    build:
      context: ./mediasoup-sfu
      dockerfile: Dockerfile
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    ports:
      - 15000-15100:15000-15100/udp
      - 5959:5959
    environment:
      - HOSTNAME=no1010042068022.corp.adobe.com
      - RTCMIN_PORT=15000
      - RTCMAX_PORT=15100
      - WEBPAGE_PORT=5959
      - SERVER_IP=0.0.0.0
      - OUTBOUND_LATENCY_IN_MS=400
      - ANNOUNCED_IP=${SFU_ANNOUNCED_IP}
      - OBSERVER_INTERNAL_ADDRESS=host.docker.internal:7080
    depends_on:
      - observer

  webrtc-app:
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    build:
      context: ./my-webrtc-app
      dockerfile: Dockerfile
    environment: 
      - SAMPLING_PERIOD_IN_MS=10000
    ports:
    - 9000:9000
    depends_on:
    - observer
