services:
  notebooks:
    restart: always
    build:
      context: ./my-notebooks
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./my-notebooks:/home/jovyan/work
      
  observer:
    restart: always
    image: observertc/observer:1.0.0-beta
    ports:
      - 7080:7080
    environment:
      - MICRONAUT_CONFIG_FILES=/my-config.yaml
    volumes:
      - ./observer-config/config.yaml:/my-config.yaml

  mongodb:
    image: mongo:4.2
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: always
    depends_on:
    - mongodb

  mediasoup_sfu_1:
    build:
      context: ./mediasoup-sfu
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - 15000-15100:15000-15100/udp
      - 5959:5959
    environment:
      - HOSTNAME=no1010042068022.corp.adobe.com
      - RTCMIN_PORT=15000
      - RTCMAX_PORT=15100
      - WEBSOCKET_PORT=5959
      - SERVER_IP=0.0.0.0
      - OUTBOUND_LATENCY_IN_MS=400
      - ANNOUNCED_IP=${SFU_ANNOUNCED_IP}
      - OBSERVER_INTERNAL_ADDRESS=host.docker.internal:7080
      - SFUPEER_MIN_PORT=6000
      - SFUPEER_MAX_PORT=6005
      - SFUPEER_LISTENING_HOST=mediasoup_sfu_1
      - SFU_PEERS=sfu1_to_sfu2@host.docker.internal:7171
    depends_on:
      - observer
  
  mediasoup_sfu_2:
    build:
      context: ./mediasoup-sfu
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - 15200-15300:15200-15300/udp
      - 7171:7171
    environment:
      - HOSTNAME=no1010042068022.corp.adobe.com
      - RTCMIN_PORT=15200
      - RTCMAX_PORT=15300
      - WEBSOCKET_PORT=7171
      - SERVER_IP=0.0.0.0
      - OUTBOUND_LATENCY_IN_MS=400
      - ANNOUNCED_IP=${SFU_ANNOUNCED_IP}
      - OBSERVER_INTERNAL_ADDRESS=host.docker.internal:7080
      - SFUPEER_MIN_PORT=6010
      - SFUPEER_MAX_PORT=6015
      - SFUPEER_LISTENING_HOST=mediasoup_sfu_2
      - SFU_PEERS=sfu1_to_sfu2@host.docker.internal:5959
    depends_on:
      - observer
  webrtc-app:
    build:
      context: ./my-webrtc-app
      dockerfile: Dockerfile
    environment: 
      - SAMPLING_PERIOD_IN_MS=10000
    ports:
    - 9000:9000
    depends_on:
    - observer
version: '3.3'